[package]
name = "toml-io"
version = "0.1.0"
authors = ["haghir <47360153+haghir@users.noreply.github.com>"]
edition = "2018"

[dependencies]
serde = { version = "1.0.145", features = ["derive"] }
toml = "0.7.6"
