[package]
name = "ldap"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ldap3 = "0.10.2"
tokio = {version = "1.17.0", features = ["full"]}
